# Generated by Django 2.0.6 on 2019-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldWidgetClassworkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='booleanItem',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='checkbox',
        ),
        migrations.AddField(
            model_name='superhero',
            name='abilities',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='dropDown2',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='dropDown',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='radio',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
